baseURL = "https://benoitgoujon.com/"
languageCode = "en-us"
title = "Data Super Heroes"
theme = "beautifulhugo"
enableEmoji = true

[Params]
    readingTime = true
    socialShare = true

[Author]
    name = "Beno√Æt Goujon"
    github = "goujonbe"
    twitter = "benoit_goujon"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
